### ISSUE TITLE
Some images in inspo.org are not correctly displayed

### ISSUE THREAD

**Issue by 552020** [formation-tools/product#1]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/60273337/162942535-8a9b564e-cc68-44bb-8a9b-1401b83871c8.png">

**Comment by vidbina** [comment]
Good find. Fixed with https://github.com/formation-tools/product/commit/9706cb9fc123d5dbf59e46cdaf944b9b1fc16172 where I removed some spacing in the image file names.
